// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

#export-func sumEvenFiboNumbers = sumEvenFiboNumbers

const int MAX_FIBO = 4000000;

long sumEvenFiboNumbers()
{
	long sum;
	int temp, curr, prev;

	sum  = 0;
	curr = 1;
	prev = 1;

	while (curr < MAX_FIBO) {
		temp  = curr;
		curr += prev;
		prev  = temp;

		if (curr % 2 == 0)
			sum += ((long) curr);
	}

	return sum;
}
